Setup project files
pradmon/MyPortfolio pull request #1
Opened 2023-03-25 16:51 UTC by pradmon

In this branch  I did:

- [ ] Add Html files.
- [ ] Add CSS files.
- [ ] Edit Readme files.
- [ ] Add Linters.

2023-03-29 20:07 UTC, AdnanOlarmmi requested changes
Hi @pradmon, 

This is Adnan Is-haq, your beloved code reviewer,

You've done a very good job so far, but a few things still need to be worked on before moving on to the next project, but you're so close!

![You're Almost there, funny one eyed alien](https://user-images.githubusercontent.com/41163571/217957948-6d8d9f33-125c-4724-954f-330eed60533c.gif)

## Highlights
- Nice UI design.
- Nice one using flex to arrange the items. 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
- N/A

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-29 20:07 UTC, AdnanOlarmmi commented on index.html
- As per the design. 

- Your design
![image](https://user-images.githubusercontent.com/41163571/228651893-085e2c34-2c9c-45b6-84a2-29c1c34713de.png)

- Figma design
<img width="236" alt="right" src="https://user-images.githubusercontent.com/41163571/228056013-322e1f2c-93c1-4f1b-b7e0-46a3b6a945c5.png">

- More information at the bottom 👇  wherever appropriate, 🏃

2023-03-29 20:07 UTC, AdnanOlarmmi commented on index.html
> +    <header class="header">
- [ ] 1. Kindly include a logo, like it is in the design, if you can't find one, then I'll advise that you use your first name or your alias, and ensure it is enclosed in an anchor tag `<a></a>` 🙂

2023-03-29 20:07 UTC, AdnanOlarmmi commented on index.html
> +        </nav>
- [ ] 2. Nice one fixing the hamburger in between a `nav` element, what is left for us is to move it to the right a bit to ensure we have a pixel-perfect design as you'll soon be doing in your job 😉.

2023-03-29 20:07 UTC, AdnanOlarmmi commented on index.html
> +                <button type="button" class="menu-button"><img src="./img/let-connect.png" alt="menu-image" width="200"></button>
- [ ] 3. This should be a text sir and not an image. 😃 it should be a text wrapped in between an anchor (`<a></a>`) tag. with the same design guidelines, like font size, color, and the like.

2023-03-29 20:07 UTC, AdnanOlarmmi commented on index.html
> +            </ul>
- [ ] 4. I really applaud you for fixing these icons like this, one more thing left. please let us reduce the spacing between the icons a bit, to achieve a pixel-perfect design.

2023-03-29 20:07 UTC, AdnanOlarmmi commented on style.css
> +  display: flex;
- [ ] It is noticed that `display: flex` property is repeated multiple times, Kindly let us stick to the DRY principle by not repeating a property more than it should 🙂. This can be done by having a class called `.flex-row` or `.flex-column` then assigning it wherever possible as a class name in your `html` markup code.
```
.flex-row {
  display: flex;
}

.flex-column {
  display: flex;
  flex-direction: column;
}
```
- And kindly attend to any repetitions in your code 🙂.

2023-03-30 00:05 UTC, mahbubul14 approved these changes
# Project Approved :trophy: :tada: 

Hi @pradmon, 

Your project is complete!  You have done it exceptionally well. it's time to merge it :100: 
Congratulations! 🎉 

### To Highlight :+1: 

:heavy_check_mark: No linter error.
:heavy_check_mark: Descriptive readme file.
:heavy_check_mark: Well-implemented suggestions by the previous reviewer.

### Optional suggestions :arrow_down_small: 

Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better.

- [ ] The commit message should be written in the imperative tense and the first letter should also be capitalized. `Ex: "Fix bug" instead of "bug fixed".` [For more details...](https://www.freecodecamp.org/news/level-you-up-to-awesome-commit-messages-a85558cb90e8)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification. You can also connect with me on [slack](https://microverse-students.slack.com/team/U01J39GL614)

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2023-03-30 01:57 UTC, pradmon commented
Thanks so much,  Mahbub Alam.

On Wed, Mar 29, 2023 at 7:05 PM Mahbub Alam ***@***.***>
wrote:

> ***@***.**** approved this pull request.
> Project Approved 🏆 🎉
>
> Hi @pradmon <https://github.com/pradmon>,
>
> Your project is complete! You have done it exceptionally well. it's time
> to merge it 💯
> Congratulations! 🎉
> To Highlight 👍
>
> ✔️ No linter error.
> ✔️ Descriptive readme file.
> ✔️ Well-implemented suggestions by the previous reviewer.
> Optional suggestions 🔽
>
> Every comment with the [OPTIONAL] prefix is not crucial enough to stop the
> approval of this PR. However, I strongly recommend you take them into
> account as they can make your code better.
>
>    - The commit message should be written in the imperative tense and the
>    first letter should also be capitalized. Ex: "Fix bug" instead of "bug
>    fixed". For more details...
>    <https://www.freecodecamp.org/news/level-you-up-to-awesome-commit-messages-a85558cb90e8>
>
> Cheers and Happy coding!👏👏👏
>
> Feel free to leave any questions or comments in the PR thread if something
> is not 100% clear.
> Please, remember to tag me in your question so I can receive the
> notification. You can also connect with me on slack
> <https://microverse-students.slack.com/team/U01J39GL614>
> ------------------------------
>
> *As described in the Code reviews limits policy
> <https://microverse.zendesk.com/hc/en-us/articles/1500004088561> you have a
> limited number of reviews per project (check the exact number in your
> Dashboard). If you think that the code review was not fair, you can request
> a second opinion using this form <https://airtable.com/shrQAqnBwek5a0O0s>.*
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/pradmon/MyPortfolio/pull/1#pullrequestreview-1364143104>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ACNGOCWX3JW4PHFRRQN74BDW6TE57ANCNFSM6AAAAAAWHUD6UI>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-03-30 02:06 UTC, merged