Add Works section and About myself section
pradmon/MyPortfolio pull request #2
Opened 2023-04-01 20:27 UTC by pradmon

In this branch I did:

- [ ] Add Works section in this area.
- [ ] Add About myself section.

2023-04-01 21:13 UTC, MeqdamAlqudah requested changes
Hi @pradmon 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
![image](https://user-images.githubusercontent.com/74744787/229314169-93e563c5-67ec-4c94-96e6-3c7baba16d7d.png)
## Highlights
:+1: design 
:+1: semantic tags

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- check the design twice and make sure every thing match it 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-01 21:13 UTC, MeqdamAlqudah commented on index.html
> +                    <li><a class="text-decoration">Back End Dev</a></li>
- [ ] Please the card background should match the Figma design, as you can see in the design each card should have a white background .
Your design  
![image](https://user-images.githubusercontent.com/74744787/229313376-46db743a-c703-4664-ac7a-01fc74a4e65a.png)

Figma 
![image](https://user-images.githubusercontent.com/74744787/229313360-5b9b3c14-60ac-4532-af72-e13f2c229c66.png)

2023-04-01 21:13 UTC, MeqdamAlqudah commented on index.html
> +                    <li><a class="text-decoration">Back End Dev</a></li>
- [ ] Please each card should be aligned using flexbox as it is better for one-directional aligning.
![image](https://user-images.githubusercontent.com/74744787/229313440-6299c2bd-d91d-4fd8-b052-c948021d5b80.png)

2023-04-01 21:13 UTC, MeqdamAlqudah commented on index.html
> +                    <li><img src="img/circle.png" alt="circle image"></li>
- [ ] Please the work section should have the margins (top, bottom, left, right) defined in the design, mobile version should be responsive until the desktop screen size.
Your design 
![image](https://user-images.githubusercontent.com/74744787/229313485-7f84aedf-0f9a-449b-8d18-2a2820c3296b.png)
Figma 
![image](https://user-images.githubusercontent.com/74744787/229313547-785da60c-96d2-4251-ae67-51f76c4baa17.png)

2023-04-01 21:13 UTC, MeqdamAlqudah commented on index.html
> +                    some
- [ ] Please it is better to use semantic tags, it would be better to use `p` tag to wrap this text since it is better for SEO. 
![image](https://user-images.githubusercontent.com/74744787/229313615-2ca48fdb-0217-47c3-a5eb-a738b45be2c2.png)

2023-04-01 21:13 UTC, MeqdamAlqudah commented on index.html
> +                    of my work and experience!. If you like what you see and have a project you need coded, don't
- [ ] Please `the about myself` section should have the margins (top, bottom, left, right) defined in the design.
- There is a weird distance around the about myself section,
- the distance between the text and the let's connect button doesn't match the design.

Your design 
![image](https://user-images.githubusercontent.com/74744787/229313758-17e45045-664f-4356-8ded-3c65c886a41c.png)

Figma 
![image](https://user-images.githubusercontent.com/74744787/229313773-892c9640-bca8-42f1-8967-207e35a386f6.png)

- [ ] Please `about myself` section should use the font and colors (background and font) defined for the template. 
- The title and the text colors don't match the design.
Your design 
![image](https://user-images.githubusercontent.com/74744787/229313921-65e76390-727a-4703-8b53-f7501f993dca.png)

Figma 
![image](https://user-images.githubusercontent.com/74744787/229313910-5bdcd986-4bf8-47cc-9275-b7dcee0eb1f9.png)

- [ Optional ]  The order of the icons doesn't match the design.
Your design
![image](https://user-images.githubusercontent.com/74744787/229314107-4bb46757-7833-4129-a115-b91ba0528082.png)

Figma 
![image](https://user-images.githubusercontent.com/74744787/229314121-0fa40089-5b80-44d5-a8a7-efde6913be7d.png)

2023-04-02 01:13 UTC, Owusu-Desmond requested changes
Hi @pradmon , :wave: 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some changes you still need to work on before you move on to the next project but you are almost there.

<img src="https://media1.giphy.com/media/KyBesf8kNT6s88SEgb/giphy.gif"/>

 ## Highlights :+1: 
:heavy_check_mark: Good commit history.
:heavy_check_mark: No linter errors.
:heavy_check_mark: Your project is well documented


 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-02 01:13 UTC, Owusu-Desmond commented on index.html
> +                </div>
- [ ] From the project requirements, you should stick to the [Figma design](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=39%3A122&t=Tt1vCN6lfPrkflxz-0), As requested by the previous reviewer, The `About Myself` section text  color and the section border-right-radius does not match the [Figma design](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=39%3A122&t=Tt1vCN6lfPrkflxz-0) :blush: 

| Your Design |Figma Design |
| :---:   | :---: | 
| ![image](https://user-images.githubusercontent.com/92303891/229325139-e618d84b-152c-4789-ab19-69e9641e302d.png)| ![image](https://user-images.githubusercontent.com/92303891/229325057-171e1988-49a0-4af8-bdc2-d3f2371f516e.png)|

2023-04-02 02:03 UTC, pradmon commented
Good evening, the modifications have already been made and the file has
been sent for review.
Thank you

On Sat, Apr 1, 2023 at 8:14 PM Desmond Owusu Ansah ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
>
> Hi @pradmon <https://github.com/pradmon> , 👋
>
> Great work on making the changes requested by a previous reviewer 👏
> You've done well implementing some of the requested changes, but there are
> still some changes you still need to work on before you move on to the next
> project but you are almost there.
>
>
> <https://camo.githubusercontent.com/4b7fa974fd5b17f3b4fbbeb2c7055d542a1e61178c271b52f9843ffbd39cca89/68747470733a2f2f6d65646961312e67697068792e636f6d2f6d656469612f4b7942657366386b4e5436733838534567622f67697068792e676966>
> Highlights 👍
>
> ✔️ Good commit history.
> ✔️ No linter errors.
> ✔️ Your project is well documented
> Required Changes ♻️
>
> *Check the comments under the review.*
> Optional suggestions
>
> *Every comment with the [OPTIONAL] prefix won't stop the approval of this
> PR. However, I strongly recommend you to take them into account as they can
> make your code better. Some of them were simply missed by the previous
> reviewer and addressing them will really improve your application.*
>
> Cheers and Happy coding!👏👏👏
>
> Feel free to leave any questions or comments in the PR thread if something
> is not 100% clear.
> Please, remember to tag me in your question so I can receive the
> notification.
>
> *Please, do not open a new Pull Request for re-reviews. You should use the
> same Pull Request submitted for the first review, either valid or invalid
> unless it is requested otherwise.*
> ------------------------------
>
> *As described in the Code reviews limits policy
> <https://microverse.zendesk.com/hc/en-us/articles/1500004088561> you have a
> limited number of reviews per project (check the exact number in your
> Dashboard). If you think that the code review was not fair, you can request
> a second opinion using this form <https://airtable.com/shrQAqnBwek5a0O0s>.*
> ------------------------------
>
> In index.html
> <https://github.com/pradmon/MyPortfolio/pull/2#discussion_r1155221583>:
>
> > +                <div class="title">
> +                    <h2>About Myself</h2>
> +                </div>
>
>
>    - From the project requirements, you should stick to the Figma design
>    <https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=39%3A122&t=Tt1vCN6lfPrkflxz-0>,
>    As requested by the previous reviewer, The About Myself section text
>    color and the section border-right-radius does not match the Figma
>    design
>    <https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=39%3A122&t=Tt1vCN6lfPrkflxz-0>
>    😊
>
> Your Design Figma Design
> [image: image]
> <https://user-images.githubusercontent.com/92303891/229325139-e618d84b-152c-4789-ab19-69e9641e302d.png> [image:
> image]
> <https://user-images.githubusercontent.com/92303891/229325057-171e1988-49a0-4af8-bdc2-d3f2371f516e.png>
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/pradmon/MyPortfolio/pull/2#pullrequestreview-1368004274>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ACNGOCTLBMSN3OF3V2DE2M3W7DHF7ANCNFSM6AAAAAAWP22EAA>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-04-02 02:07 UTC, binhussen commented
@pradmon, Kindy would arrand the padding and text color to `#172B4D` as suggested, by prevois reviwer

2023-04-02 02:17 UTC, binhussen requested changes
Hi @pradmon , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't been addressed yet.
<img src="https://media0.giphy.com/media/UdaSUYClr92cjWpeVx/giphy.gif"/>

## Highlights

- All linter checks passed ✔️
- Descriptive pull request ✔️
- Used GitHub flow ✔️


 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-02 02:17 UTC, binhussen commented on index.html
> +                </div>
- Kindly, update the about section color to `#172B4D`, to stick the Figma design :+1: as the previous code reviewer suggested you

2023-04-02 03:12 UTC, Strangeal requested changes
Hi @pradmon, 

Great work implementing the requested change by the previous reviewers👏 , while doing that I think you introduced a new bug into your code which I have highlighted below.

![Alt Text](https://media.giphy.com/media/l2Je9zHYveK012EVi/giphy.gif)

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-02 03:12 UTC, Strangeal commented on style.css
> +  padding: 8px 1px;
- [ ] Kindly change the `padding` to match that of the Figma template. Currently what you have doesn't make a great user experience. See the screenshot below for more details:

Figma:
<img width="335" alt="Screenshot 2023-04-02 at 03 03 17" src="https://user-images.githubusercontent.com/107192076/229328897-71376650-45af-4cd7-bfd4-9dd5d2d3840d.png">

Your design:
<img width="326" alt="Screenshot 2023-04-02 at 03 02 21" src="https://user-images.githubusercontent.com/107192076/229328905-efe9cb25-4a87-4cce-bffb-22c9330cb695.png">

- [ ] Also, please align the button text to the center for a great user experience.

2023-04-02 04:19 UTC, franclobo approved these changes
Hi @pradmon, 

# STATUS: APPROVED 😃

![git-merge](https://user-images.githubusercontent.com/58642949/229331126-32e23894-bb17-43bd-b407-e14c7de8acbd.gif)

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights

- No linter errors ✔️ 
- Correct Github flow ✔️ 
- Descriptive PR ✔️ 

## Optional suggestions

- Instead of all code reviewers have made some suggestions to have a design similar to the Figma template there are some details we need to complete to be similar to the Figma template, please 🙏🏽 complete them all 👇🏽

-  **[OPTIONAL]** The header have a withe background with a border radius at the bottom-left 👇🏽 

| Figma template | Your design |
|---|---|
| ![image](https://user-images.githubusercontent.com/58642949/229330593-15891821-24a9-4f74-8c72-74e1bdbb2120.png) | ![image](https://user-images.githubusercontent.com/58642949/229330610-8f3a89ae-caed-4130-9959-0c7f695a8510.png) |

-  **[OPTIONAL]** The `About Myself section has a border radius on the top-right corner, the correct color of the title is `#172B4D` the correct font size of `LET'S CONNECT` is `16px`, the `Get my resume` button has different margins, padding, and font size, and the languages have a background 👇🏽 

| Figma template | Your design |
|---|---|
| ![image](https://user-images.githubusercontent.com/58642949/229330972-e01f9533-fed5-44f0-b050-5c8e725513d4.png) | ![image](https://user-images.githubusercontent.com/58642949/229330988-94940688-30b9-4561-8a88-6cd6203e6600.png) |
| ![image](https://user-images.githubusercontent.com/58642949/229331002-e704ecc1-a39c-4b71-bc06-c2f4bdc41288.png) | ![image](https://user-images.githubusercontent.com/58642949/229331012-23f60d81-0f7f-4b9d-ae19-395f2a86b742.png) |

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-02 04:19 UTC, franclobo commented on index.html
> +                                        JavaScript
- **[OPTIONAL]** Please 🙏🏽  wrap the text of the div in a `p` tag for the best practices of HTML & CSS.

2023-04-02 04:19 UTC, franclobo commented on index.html
> +                                        Html
- **[OPTIONAL]** Please 🙏🏽  wrap the text of the div in a `p` tag for the best practices of HTML & CSS.

2023-04-02 04:19 UTC, franclobo commented on index.html
> +                                        Css
- **[OPTIONAL]** Please 🙏🏽  wrap the text of the div in a `p` tag for the best practices of HTML & CSS.

2023-04-02 04:27 UTC, merged